import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    // Header & Navigation
    home: "Home",
    dashboard: "Dashboard",
    manageUsers: "Manage Users",
    projects: "Projects",
    allTasks: "All Tasks",
    reports: "Reports",
    profile: "Profile",
    profileSubtitle: "Manage your personal info and account security",
    profileCreated: "Created",
    profileRoleLevel: "Role Level",
    profilePersonalInfo: "Personal Info",
    profileUsername: "Full Name",
    profilePhone: "Phone",
    profileEmailDisabled: "Email (Cannot be changed)",
    profileEmail: "Email",
    profileChangePassword: "Change Password (If desired)",
    profileCurrentPassword: "Current Password",
    profileNewPassword: "New Password",
    profileConfirmPassword: "Confirm New Password",
    profileSaving: "Saving...",
    profileSaveChanges: "Save Changes",
    profileUpdateSuccess: "Profile updated successfully!",
    profileLoadFailed: "Failed to load user profile. Please try again.",
    profileUsernameEmpty: "Full name cannot be empty",
    currentPasswordRequired: "Please enter your current password",
    profileUpdateFailed: "Failed to update profile. Please try again.",
    profileLeaderLabel: "Leader",
    profileLeaderPlaceholder: "-- Select Leader --",
    profileLeaderLockedNotice:
      "You have already set your leader and cannot change it.",
    profileLeaderNotice:
      "You can select your leader only once. Once saved, it cannot be changed.",
    myTask: "My Task",
    personalTask: "Personal Tasks",
    themes: "Themes",
    appearance: "Appearance",
    appearanceLight: "Light",
    appearanceDark: "Dark",
    appearanceAuto: "Auto",
    clickupTheme: "Accent Theme",
    accentBlue: "Blue",
    accentPurple: "Purple",
    accentPink: "Pink",
    accentViolet: "Violet",
    accentIndigo: "Indigo",
    accentOrange: "Orange",
    accentTeal: "Teal",
    accentBronze: "Bronze",
    accentMint: "Mint",
    accentGold: "Gold",
    myActivity: "My Activity",
    myActivitySubtitle: "View and track your personal activity history",
    signOut: "Sign Out",
    login: "Login",
    loading: "Loading...",
    notifications: "Notifications",
    markAllAsRead: "Mark all read",
    noNotifications: "No notifications yet",
    unread: "Unread",
    all: "All",
    clearAll: "Clear All",
    justNow: "Just now",
    minutesAgo: "m ago",
    hoursAgo: "h ago",
    daysAgo: "d ago",
    deleteNotification: "Delete",
    newTaskAssigned: "New Task Assigned",
    projectStatusUpdated: "Project Status Updated",
    systemNotification: "System Notification",
    notifAssignedTeamLeader: "Assigned as Team Leader",
    notifAssignedTeamLeaderMsg:
      'You have been assigned as Team Leader for project "{project}"',
    notifNewTaskInProject: "New Task in Project",
    notifNewTaskInProjectMsg: 'New task "{task}" in project "{project}"',
    notifNewTaskAssignedMsg:
      'You have been assigned a new task: "{task}" in project "{project}"',
    notifTaskStatusUpdated: "Task Status Updated",
    notifTaskStatusUpdatedMsg:
      'Task "{task}" in project "{project}" status changed to "{status}"',
    notifProjectUpdated: "Project Updated",
    notifProjectUpdatedMsg: 'Project "{project}" has been updated',
    notifProjectReviewing: "Project Reviewing",
    notifProjectReviewingMsg: 'Project "{project}" is currently reviewing',
    notifNewComment: "New Comment on Task",
    notifNewCommentMsg: 'New comment on task "{task}"',
    personalTask: "Personal Tasks",

    // Login Page
    loginTitle: "Login",
    emailLabel: "Email",
    passwordLabel: "Password",
    emailPlaceholder: "Enter Your Email",
    passwordPlaceholder: "Enter Your Password",
    fillAllFields: "Please Fill In All Fields",
    loginSuccess: "Login Successful! Redirecting...",
    loginFailed: "Login Failed. Please Try Again.",
    invalidCredentials: "Invalid email or password",
    accountSuspended:
      "Your account has been suspended. Please contact the administrator.",
    accountExpired:
      "Your account has expired. Please contact the administrator.",
    accountNotStarted: "This account will be active starting from {startDate}.",
    forgotPasswordLink: "Forgot Password?",
    resetPasswordTitle: "Reset Password",
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm New Password",
    resetSuccess: "Password reset successfully! Redirecting to login...",
    passwordsMismatch: "Passwords do not match!",
    otpCodeLabel: "OTP",
    otpCodePlaceholder: "6-digit OTP code",
    sendOtpBtn: "Send OTP",

    // Home Page
    homeMessage: "Home For Unregistered Users",

    // Dashboard Page
    dashboardTitle: "Dashboard",
    allUsers: "All Users",
    allMyTasks: "All My Tasks",
    manageUsersLink: "Manage Users →",
    allProjects: "All Projects",
    viewProjectsLink: "View Projects →",
    totalTasks: "Total Tasks",
    completedPrefix: "Completed: ",
    overdueTasks: "Overdue Tasks",
    overdueProjects: "Overdue Projects",
    actionRequired: "Action Required",
    taskStatus: "Task Status",
    projectStatus: "Project Status",
    pending: "Pending",
    inProgress: "In Progress",
    reviewing: "Reviewing",
    completed: "Completed",
    recentActivity: "Recent Activity",
    systemAdmin: "System Admin",
    loggedIn: "Logged In",
    minuteAgo: "1 Minute Ago",
    viewAll: "View All",

    // Dashboard Cards
    manageUsersBtn: "Manage Users",
    projectsTitle: "Projects",
    reportsTitle: "Reports",
    "Project Calendar Title": "Project Calendar",
    projectCalendarDesc: "Track project deadlines and statuses systematically",

    // ManageUsers Page
    manageUsersTitle: "Manage Users",
    addUserBtn: "Add User",
    roleFilterAll: "All Roles",
    statusFilterAll: "All Statuses",
    activeLabel: "Active",
    suspendedLabel: "Suspended",
    searchUser: "Search User",
    searchPlaceholder: "Search by Name or Email...",
    searchBtn: "Search",
    showText: "Show",
    entriesPerPageText: "Entries",
    searchText: "Search:",
    colUser: "User",
    colEmail: "Email",
    colRole: "Role",
    colStatus: "Status",
    colLastLogin: "Last Login",
    colManage: "Manage",
    noUsersText: "No Users Found",
    showingText: "Showing",
    toText: "to",
    ofText: "of",
    entriesText: "Entries",
    prevText: "Previous",
    nextText: "Next",
    importUsersBtn: "Import Users",
    downloadTemplateBtn: "Download Template",
    importSuccess: "Users imported/updated successfully!",
    importFailed: "Import failed!",
    importConfirmTitle: "Confirm User Import",
    importConfirmDesc:
      "Are you sure you want to import users from {filename}? ({count} users found)",
    importResultTitle: "Import Completed",
    importResultDesc:
      "Successfully imported {imported} new users and updated {updated} existing users.",
    importPreviewTitle: "Review Users Before Import",
    importPreviewSub: "File:",
    importPreviewTotal: "Total",
    importTotalCount: "Total Records",
    importNewUsers: "New Users",
    importUpdateUsers: "Update Existing",
    importChangedUsers: "Data Changed",
    importUnchangedUsers: "No Changes",
    importInvalidUsers: "Incomplete/Invalid",
    importActionCol: "Import Action",
    importActionCreate: "New Account",
    importActionUpdate: "Update Account",
    importActionChanged: "Update (Changed)",
    importActionUnchanged: "No Change (Skip)",
    importActionInvalid: "Skip (Missing data)",
    importConfirmSummary: "Ready to import",
    importChangedOnlyNotice: "Only new and changed records will be updated to optimize performance.",
    importInvalidSkipped: "Incomplete rows skipped:",
    importingProgress: "Importing users...",
    exportUsersBtn: "Export Users",

    // ManageUsers Modal
    addEditUserTitle: "Add / Edit User",
    editUserTitle: "Edit User Info",
    addUserTitle: "Add New User",
    backBtn: "← Back",
    modalEmailLabel: "Email",
    modalPasswordLabel: "Password",
    modalPasswordPlaceholder: "Set Password",
    modalPasswordEditPlaceholder: "Leave Blank to Keep Current",
    modalFirstNameLabel: "First Name",
    modalLastNameLabel: "Last Name",
    modalPhoneLabel: "Phone Number",
    modalStartDateLabel: "Start Date",
    modalExpireDateLabel: "Expiration Date",
    modalStartDatePlaceholder: "No Start Date (Immediate)",
    modalExpireDatePlaceholder: "No Expiration (Lifetime)",
    colValidity: "Account Validity",
    validForever: "Lifetime",
    expiredLabel: "Expired",
    notStartedLabel: "Pending Start",
    modalAvatarLabel: "Profile Picture",
    modalChoosePhoto: "Choose Photo",
    modalRemovePhoto: "Remove Photo",
    modalRoleLabel: "Role",
    modalLeaderLabel: "Leader",
    modalLeaderPlaceholder: "-- Clear --",
    modalActiveLabel: "Active",
    modalCancelBtn: "Cancel",
    modalSaveBtn: "Save Changes",
    modalCreateBtn: "Create User",
    uploadPhotoBtn: "Upload Photo",
    modalStatusLabel: "Status",
    statusActive: "Active",
    statusSuspended: "Suspended",
    cannotChangeSelfStatus: "Cannot change your own status",
    youBadge: "You",
    leaderBadge: "Leader",

    // ManageUsers messages
    fillRequiredFields: "Please Fill In All Required (*) Fields",
    userUpdatedSuccess: "User Updated Successfully!",
    userCreatedSuccess: "New User Account Created Successfully!",
    userAddFailed: "Unable to Add User",
    userUpdateFailed: "Unable to Update User",
    suspendConfirm: "Do You Want to Suspend User",
    activateConfirm: "Do You Want to Reactivate User",
    confirmSuffix: "?",
    statusChangeFailed: "Unable to Change User Status",
    deleteConfirm: "Are You Sure You Want to Permanently Delete User",
    deleteSuffix: "from the System?",
    deleteFailed: "Unable to Delete User",
    fillRequiredFieldsProject:
      "Please fill in all fields (Title, End Date, Team Leader)",
    projectCreatedSuccess:
      "New project created and notification sent to Team Leader successfully!",
    projectCreateFailed: "Unable to create project",
    projectUpdatedSuccess: "Project information updated successfully!",
    projectUpdateFailed: "Unable to update project",
    noPermissionDeleteProject: "No permission to delete project (Admin only)",
    projectDeletedSuccess: "Deleted project and all related data successfully!",
    projectDeleteFailed: "Unable to delete project",
    editProjectTitle: "Edit Project",
    modalProjectTitle: "Project Title",
    modalProjectStatus: "Status",
    modalProjectPriority: "Priority",
    modalProjectEndDate: "End Date",
    modalProjectTeamLeader: "Team Leader",
    modalSaveProject: "Save Changes",
    projectDetailsTitle: "Project Details",
    projectDetailsName: "Project Name",
    projectDetailsDueDate: "Due Date",
    projectDetailsLeader: "Team Leader",
    projectDetailsManager: "Project Manager",
    projectDetailsProgress: "Overall Progress",
    projectDetailsTaskList: "Project Tasks List",
    projectDetailsNoTasks: "No tasks in this project",
    projectDetailsClose: "Close Window",
    projectDetailsEdit: "Edit This Project",
    "Add Task": "Add Task",

    // Projects Page
    projectManagementTitle: "Project Management",
    projectFlowSubtitle: "Project management structure according to Flowchart",
    searchProjectPlaceholder: "Search projects by name...",
    createProjectBtn: "+ Create New Project",
    createProjectTitle: "Create New Project",
    createProjectBtnSubmit: "Create Project",
    projectListTitle: "Project List",
    colProjectName: "Project Name",
    colProgress: "Progress",
    colPriority: "Priority",
    colTeamLeader: "Team Leader",
    colDetailAction: "Detail / Action",
    viewBtn: "View",
    editBtn: "Edit",
    deleteBtn: "Delete",
    noProjectsFound: "No projects found",
    tableView: "Table View",
    boardView: "Board View",
    statusPending: "Pending",
    statusInProgress: "In Progress",
    statusReview: "Reviewing",
    statusCompleted: "Completed",
    endDateLabel: "End Date",
    deleteProjectConfirmTitle: "Confirm Project Deletion?",
    deleteUserConfirmTitle: "Confirm User Deletion?",
    deleteProjectConfirmDesc1: "The system will delete the project ",
    deleteProjectConfirmDesc2:
      " and perform a Cascade Delete on all related data (Tasks, Comments, Files).",
    deleteUserSuccess: "User deleted successfully!",
    cancelBtn: "Cancel",
    confirmDeleteBtn: "Confirm Delete",
    confirmBtn: "Confirm",
    sortByPriorityLabel: "Sort Priority",
    sessionTimeoutTitle: "Session Expiration Warning",
    sessionTimeoutDesc:
      "Your login session is about to expire in {seconds} seconds. Would you like to continue using the web or exit?",
    sessionTimeoutStayBtn: "Continue using the website",
    sessionTimeoutExitBtn: "Exit",
    CreateTask: "Create Task",
    "Create Task": "Create Task",

    // Activity Page
    activityLogsTitle: "System Activity Logs",
    activityLogsSubtitle: "Monitor and track all system transaction logs",
    searchActivityPlaceholder: "Search details...",
    allActivities: "All Activities",
    aboutProjects: "About Projects & Tasks",
    aboutUsers: "About Users",
    aboutSystem: "About System / Others",
    refreshBtn: "Refresh",
    loadingActivities: "Loading activity logs...",
    colDoneBy: "Done By:",
    firstTimeResetTitle: "First Time Reset Password",
    firstTimeResetDesc:
      "Please change your password for safety before getting started",
    updatingPassword: "Updating...",
    saveNewPassword: "Save New Password",
    firstTimeResetSuccess:
      "Password updated successfully! Redirecting to dashboard...",
    firstTimeResetFailed: "Failed to reset password.",
    forceResetPrompt: "Please reset your password on first login",
    unassigned: "Unassigned",
    viewTaskDetail: "View Task Detail",
    Login: "Login",
    "Create New Project": "Created New Project",
    "Edit Project": "Edited Project",
    "Delete Project": "Deleted Project",
    "Create Task Success": "Created Task",
    "Update Task Status": "Updated Task Status",
    "Update Task Details": "Updated Task Details",
    "Edit Task": "Edited Task",
    "Delete Task": "Deleted Task",
    Logout: "Logout",
    "Reset Password": "Reset Password",
    "Reset Password First Time": "Reset Password First Time",
    "Import Users": "Imported Users",
    "Create User": "Created User",
    "Edit User": "Edited User Details",
    "Delete User": "Deleted User",
    "Suspend User": "Suspended User",
    "Activate User": "Activated User",
    taskDetailsTitle: "Task Details",
    createTaskTitle: "Create Task",
    createTaskBtn: "Create Task",
    taskProjectLabel: "Project",
    taskNameLabel: "Task Name",
    taskNamePlaceholder: "Enter task name...",
    taskTypeLabel: "Task Type",
    taskTypeTranslate: "Translate",
    taskTypeStoryboard: "Storyboard & Script",
    taskTypeGraphicDesign: "Graphic & Design",
    taskTypeAnimation: "Animation",
    taskTypeVideoEdit: "Video Editing",
    taskTypeDevelopment: "Development",
    taskTypeOthers: "Others",
    customTaskTypeLabel: "Specify custom task type *",
    customTaskTypePlaceholder: "Enter custom task type",
    taskDescLabel: "Description",
    taskDescPlaceholder: "Enter task details...",
    taskPriorityLabel: "Priority",
    priorityHigh: "High",
    priorityMedium: "Medium",
    priorityLow: "Low",
    optionalText: "Optional",
    taskDueDateLabel: "Due Date",
    taskAssigneeLabel: "Assignee",
    selectAssignee: "Select Assignee",
    taskStatusLabel: "Task Status",
    noDescription: "-- No Description --",
    noAssignee: "-- Unassigned --",
    updateStatusBtn: "Update Status",
    taskStatusPending: "Pending",
    taskStatusInProgress: "In Progress",
    taskStatusReviewing: "Reviewing",
    taskStatusCompleted: "Completed",
    manageUsersDesc: "Manage system users and access permissions",
    projectManagementDesc: "Manage projects and assigned team members",

    // About & Contract Pages
    aboutTitle: "About RNM Task System",
    aboutSubtitle: "Modern platform for team project and task management",
    aboutVisionTitle: "Our Mission & Vision",
    aboutVisionDesc:
      "RNM Task Management is designed to elevate teamwork, enhance project transparency, and optimize task workflows through real-time updates and seamless activity tracking.",
    featureAnalyticsTitle: "Real-time Analytics & Dashboard",
    featureAnalyticsDesc:
      "Track total active users, projects, and pending or overdue tasks with intuitive visual charts.",
    featureWorkflowTitle: "Structured Task Workflows",
    featureWorkflowDesc:
      "Organize tasks by status (Pending, In Progress, Reviewing, Completed) and assign priority levels.",
    featureAccessTitle: "Role-Based Access Control",
    featureAccessDesc:
      "Granular permissions for Admins, Team Leaders, Translators, and Video Editors.",
    featureAuditTitle: "Comprehensive Activity Logs",
    featureAuditDesc:
      "Transparent audit trail tracking every project modification, user creation, and status update.",
    techStackTitle: "Powered by Modern Technology",

    contractTitle: "Contact Us & Support",
    contractSubtitle:
      "Have questions or need assistance? Reach out to our dedicated support team.",
    contactInfoTitle: "Contact Information",
    contactAddressLabel: "Office Address",
    contactAddressVal: "------------------------",
    contactEmailLabel: "Email Support",
    contactPhoneLabel: "Phone Number",
    contactHoursLabel: "Operating Hours",
    contactHoursVal: "Mon - Fri: 09:00 - 18:00 (ICT)",
    sendMessageTitle: "Send Us a Message",
    formFullName: "Full Name",
    formFullNamePlaceholder: "Enter your full name",
    formEmail: "Email Address",
    formEmailPlaceholder: "Enter your email address",
    formSubject: "Subject",
    formSubjectPlaceholder: "What is your inquiry about?",
    formMessage: "Message",
    formMessagePlaceholder: "Type your message here...",
    sendMessageBtn: "Send Message",
    sendMessageSuccess:
      "Thank you for reaching out! Your message has been sent successfully.",
    colDetails: "Details",
    colAction: "Action",
    colTime: "Date/Time",
    landingBadge:
      "🚀 Next-generation project and task management platform for teams",
    landingHeroTitle: "Manage projects and tasks in your team",
    landingHeroTitleAccent: "Easily, systematically, all-in-one place",
    landingHeroDesc:
      "Help your team work together smoothly, track deadlines via calendar, update task statuses in real-time, and systematically record activity logs.",
    goToDashboard: "Go to Dashboard",
    getStartedBtn: "Get Started Free",
    learnMoreBtn: "Learn More",
    statProductivity: "Increase productivity",
    statAlignment: "100% Team alignment",
    statMissedDeadlines: "Reduce missed deadlines",
    landingFeaturesTitle: "Key features to make your work seamless",
    landingFeaturesDesc:
      "Our system is carefully designed to answer every step of project and task management.",
    featureProjTitle: "Manage Projects",
    featureProjDesc:
      "Create main projects, assign Team Leaders, and track overall progress automatically.",
    featureTaskTitle: "Track Tasks",
    featureTaskDesc:
      "Control task status in detail: Pending, In Progress, Reviewing, or Completed.",
    featureCalTitle: "Project Calendar",
    featureCalDesc:
      "View due dates of all projects on an interactive calendar to prevent missing deadlines.",
    featureTeamTitle: "Activity Logs",
    featureTeamDesc:
      "Track chronological actions of everyone in the system transparently, knowing every update.",
    landingCtaTitle: "Ready to elevate your team's workflow?",
    landingCtaDesc:
      "Start organizing your projects systematically today, for free!",

    // Reports Page & Role Reports
    reportsHeaderTitle: "Personal Performance Report",
    reportsHeaderDesc:
      "Analytics and performance tracking for your assigned tasks",
    adminReportTitle: "Executive System Analytics Report",
    adminReportDesc:
      "High-level executive dashboard tracking all projects, users, and overall delivery rates",
    managerReportTitle: "Project Management Delivery Report",
    managerReportDesc:
      "Comprehensive progress and delivery metrics for projects under your supervision",
    teamLeaderReportTitle: "Team Performance & Execution Report",
    teamLeaderReportDesc:
      "Execution tracking, workload breakdown, and delivery stats for your team",
    exportExcel: "Export Excel",
    printReport: "Print Report",
    totalActiveUsers: "Total Active Users",
    overallCompletionRateLabel: "Completion Rate",
    systemDeliveryEfficiency: "System Delivery Efficiency",
    systemDeliveryDesc: "Ratio of completed tasks against total system tasks",
    projectStatusBreakdownTitle: "Project Status Breakdown",
    projectStatusBreakdownDesc:
      "Detailed breakdown of all active projects by lifecycle status",
    userWorkloadMatrixTitle: "User Workload & Performance Matrix",
    userWorkloadMatrixDesc:
      "Summary of assigned task volume and completion percentage per team member",
    assignedTasksLabel: "Assigned Tasks",
    completedTasksLabel: "Completed Tasks",
    progressRateLabel: "Progress Rate",
    managedProjectsProgressTitle: "Managed Projects Progress",
    managedProjectsProgressDesc:
      "Monitor status, deadline, and progress meters for your assigned projects",
    onTrackProjectsLabel: "On-Track Projects",
    activeTeamTasksTitle: "Active Team Tasks Execution",
    activeTeamTasksDesc:
      "Track ongoing and pending tasks assigned to your team members",
    personalWorkRateTitle: "Personal Work Rate",
    personalWorkRateDesc:
      "Ratio of your completed tasks against total assigned tasks",
    workloadDistributionTypeTitle: "Workload Distribution by Type",
    workloadDistributionTypeDesc:
      "Task count categorized by task execution domain",
    myTaskPerformanceSummaryTitle: "My Task Performance Summary",
    myTaskPerformanceSummaryDesc:
      "Detailed list of all your assigned tasks with execution status",
    managedProjectsCalendar: "Managed Projects Calendar",
    managedProjectsCalendarDesc:
      "Track deadlines and statuses of projects you lead",
    myTaskCalendar: "My Task Calendar",
    myTaskCalendarDesc: "Track your personal task deadlines and statuses",
    editTaskInfoBtn: "Edit Info",
    refreshDataBtn: "Refresh",
    refreshBtn: "Refresh",
    assignedTasksText: "assigned tasks",
    manageTaskBtn: "Manage",
    noAssignedTasksText: "No assigned tasks currently",
    noActiveTeamTasksText: "No active team tasks",
    noManagedProjectsText: "No managed projects found",
    // Personal Tasks Page & Components
    personalTaskPageTitle: "Personal Tasks",
    personalTaskPageDesc:
      "Manage your personal tasks with Kanban board & Drag-and-Drop Calendar",
    kanbanViewBtn: "Kanban",
    calendarViewBtn: "Calendar",
    addNewPersonalTaskBtn: "+ Add New Task",
    editTaskPromptTitle: "Edit Task",
    newTaskPromptTitle: "Create New Task",
    taskTitleLabel: "Task Title",
    taskStatusLabel: "Status",
    dueDateOptionalLabel: "Due Date (Optional)",
    deleteTaskConfirmTitle: "Delete Task?",
    deleteTaskConfirmText: "Are you sure you want to delete this task?",
    deleteTaskConfirmBtn: "Yes, delete",
    taskDeletedSuccess: "Task deleted successfully",
    taskUpdatedSuccess: "Task updated successfully",
    taskCreatedSuccess: "New task created successfully",
    noUnscheduledTasks:
      "No unscheduled tasks (Drag any task from the calendar down here to remove its due date)",
    unscheduledTasksTrayTitle: "Tasks Without Due Date",
    unscheduledTasksTrayDesc:
      "Drag up to schedule, or drag down here to unschedule",
    dragBadge: "Drag",
    editTaskTooltip: "Edit task",
    deleteTaskTooltip: "Delete task",
    saveChangesBtn: "Save Changes",
    cancelBtnText: "Cancel",
    confirmBtnText: "Confirm",
    okBtnText: "OK",
    // Reset Password & Auth
    resetPasswordSubtitle: "Enter details and OTP code to set new password",
    backToLoginBtn: "← Back to Login",
    sendOtpSuccess: "OTP has been sent to your email!",
    sendOtpFailed: "Failed to send OTP.",
    otpVerifyFailed: "Invalid or expired OTP code.",
    welcomeBackPortal: "Welcome back to the portal",

    // Project & Task Modals & Tables
    colProjectNameUpper: "PROJECT NAME",
    colTeamLeaderUpper: "TEAM LEADER",
    colPriorityUpper: "PRIORITY",
    colStatusUpper: "STATUS",
    colDueDateUpper: "DUE DATE",
    colActionUpper: "ACTION",
    manageActionBtn: "Manage",
    editTaskInfo: "Edit Task Info",
    statusHistoryTitle: "Status History",
    searchTaskOrProjectPlaceholder: "Search by task or project...",
    allFilterOption: "All",
    totalTasksLabel: "Total Tasks",
    noTasksFoundForUser: "No Tasks Found",
    noTasksFoundDesc:
      "You do not have any tasks assigned in this status or search filter",
    noTasksInCategory: "No tasks found in this category",
    noProjectsInCategory: "No projects found in this category",
    activeCategoryLabel: "Active",
    completedCategoryLabel: "Completed",
    allCategoryLabel: "All",
    statusUpdatedSuccess: "Status updated successfully",
    // Report Tables & Performance
    myTaskPerformanceSummaryTitle: "My Task Performance Summary",
    myTaskPerformanceSummaryDesc:
      "Detailed list of all your assigned tasks with execution status",
    personalWorkRateTitle: "Personal Completion Rate",
    personalWorkRateDesc: "Percentage of completed tasks assigned to you",
    workloadDistributionTypeTitle: "Workload by Task Type",
    workloadDistributionTypeDesc:
      "Distribution of your tasks categorized by task type",
    personalReport: "Personal Report",
    teamLeaderReport: "Team Leader Report",
    managerReport: "Project Manager Report",
    adminReport: "Admin Report",
    adminReportTitle: "Executive System Analytics",
    adminReportDesc:
      "Global metrics across all projects, tasks, and team member workload",
    managerReportTitle: "Project Manager Analytics",
    managerReportDesc:
      "Overview of all managed projects, timeline progress, and delivery performance",
    teamLeaderReportTitle: "Team Leader Performance & Project Analytics",
    teamLeaderReportDesc:
      "Overview of projects and tasks executed by your team members",
    teamStatusDistribution: "Team Task Status Breakdown",
    teamStatusDistributionDesc:
      "Distribution of tasks by current status across the entire team",
    teamMemberWorkloadTitle: "Member Task Completion & Workload",
    teamMemberWorkloadDesc:
      "Comparison of assigned vs completed tasks per team member",
    projectHealthStatusTitle: "Project Status Breakdown",
    projectHealthStatusDesc:
      "Distribution of managed projects categorized by progress status",
    projectProgressOverviewTitle: "Project Progress & Delivery Rates",
    projectProgressOverviewDesc:
      "Completion percentage and delivery performance per managed project",
    taskNameLabel: "TASK NAME",
    taskProjectLabel: "PROJECT",
    taskTypeLabel: "TASK TYPE",
    taskStatusLabel: "STATUS",
    taskDueDateLabel: "DUE DATE",
    priority: "PRIORITY",
    searchWork: "Search Tasks",
    searchWorkPlaceholder: "Search by task name or project name...",
    allStatus: "All Statuses",
    allTaskTypes: "All Task Types",
    taskTypeAll: "All Task Types",
    statusFilterAll: "All Statuses",
    statusPending: "Pending",
    statusInProgress: "In Progress",
    statusReview: "Reviewing",
    statusCompleted: "Completed",
    taskTypeTranslate: "Translate",
    taskTypeStoryboard: "Storyboard & Script",
    taskTypeGraphicDesign: "Graphic & Design",
    taskTypeAnimation: "Animation",
    taskTypeVideoEdit: "Video Edit",
    taskTypeDevelopment: "Development",
    taskTypeOthers: "Others",
    noMatchingTasksFound: "No tasks found matching your filter criteria",
    clearFilters: "Clear All Filters",
    noAssignedTasksText: "No assigned tasks found",

    // Activity Log Actions (EN)
    Login: "Login",
    Logout: "Logout",
    "Create User": "Create User",
    "Suspend User": "Suspend User",
    "Activate User": "Activate User",
    "Edit User": "Edit User",
    "Soft Delete User": "Delete User",
    "Restore User": "Restore User",
    "Permanent Delete User": "Permanently Delete User",
    "Create New Project": "Create New Project",
    "Edit Project": "Edit Project",
    "Delete Project": "Delete Project",
    "Create Task Success": "Create Task",
    "Create Task": "Create Task",
    "Update Task Status": "Update Task Status",
    "Update Task Details": "Update Task Details",
    "Delete Task": "Delete Task",
    "Reset Password": "Reset Password",
    "Reset Password First Time": "Reset Password on First Login",
    "Send Email (Project Creation)": "Send Email (Project Assignment)",
    "Send Email Warning (Project Creation)":
      "Send Email Warning (Project Assignment)",
    "Send Email Failed (Project Creation)":
      "Send Email Failed (Project Assignment)",
    "Send Email (Task Creation)": "Send Email (Task Assignment)",
    "Send Email Warning (Task Creation)":
      "Send Email Warning (Task Assignment)",
    "Send Email Failed (Task Creation)": "Send Email Failed (Task Assignment)",
    "Send Email (Welcome User)": "Send Email (Welcome User)",
    "Send Email Warning (Welcome User)": "Send Email Warning (Welcome User)",
    "Send Email Failed (Welcome User)": "Send Email Failed (Welcome User)",
    "Send Email (OTP)": "Send Email (OTP)",
    "Send Email Warning (OTP)": "Send Email Warning (OTP)",
    "Send Email Failed (OTP)": "Send Email Failed (OTP)",
    "Send Email (Task Overdue to Leader)":
      "Send Email (Task Overdue to Leader)",
    "Send Email Warning (Task Overdue to Leader)":
      "Send Email Warning (Task Overdue to Leader)",
    "Send Email Failed (Task Overdue to Leader)":
      "Send Email Failed (Task Overdue to Leader)",
    เข้าสู่ระบบ: "Login",
    ออกจากระบบ: "Logout",
    สร้างผู้ใช้: "Create User",
    แก้ไขผู้ใช้: "Edit User",
    ลบผู้ใช้: "Delete User",
    สร้างโปรเจกต์ใหม่: "Create New Project",
    แก้ไขโปรเจกต์: "Edit Project",
    ลบโปรเจกต์: "Delete Project",
    สร้างงานใหม่: "Create Task",
    อัปเดตสถานะงาน: "Update Task Status",
    แก้ไขงาน: "Update Task Details",
    ลบงาน: "Delete Task",
    รีเซ็ตรหัสผ่าน: "Reset Password",
    เปลี่ยนรหัสผ่านครั้งแรก: "Reset Password on First Login",

    // Personal Task Kanban & Columns
    "TO DO": "TO DO",
    "IN PROGRESS": "IN PROGRESS",
    COMPLETED: "COMPLETED",
    "To Do": "To Do",
    "In Progress": "In Progress",
    Completed: "Completed",
    ต้องทำ: "To Do",
    กำลังทำ: "In Progress",
    เสร็จสิ้น: "Completed",

    // Activity & Logs
    activityLogsTitle: "System Activity Logs",
    activityLogsSubtitle: "Track system operations, actions, and project updates",
    searchActivityPlaceholder: "Search activities or details...",
    allActivities: "All Activities",
    aboutProjects: "Projects & Tasks",
    aboutUsers: "Users",
    aboutSystem: "System",
    colAction: "Action",
    colDetails: "Details",
    colTime: "Time",
    loadingActivities: "Loading activity logs...",
    noActivitiesFound: "No activity logs found",
  },

  th: {
    // Header & Navigation
    home: "หน้าแรก",
    dashboard: "แดชบอร์ด",
    manageUsers: "จัดการผู้ใช้งาน",
    projects: "โปรเจกต์",
    allTasks: "งานทั้งหมด",
    reports: "รายงาน",
    profile: "โปรไฟล์",
    profileSubtitle: "จัดการข้อมูลส่วนตัวและความปลอดภัยบัญชีของคุณ",
    profileCreated: "สร้างเมื่อ",
    profileRoleLevel: "ระดับสิทธิ์",
    profilePersonalInfo: "ข้อมูลส่วนตัว",
    profileUsername: "ชื่อ-นามสกุล",
    profilePhone: "เบอร์โทรศัพท์",
    profileEmailDisabled: "อีเมล (ไม่สามารถเปลี่ยนได้)",
    profileEmail: "อีเมล",
    profileChangePassword: "เปลี่ยนรหัสผ่าน (หากต้องการเปลี่ยน)",
    profileCurrentPassword: "รหัสผ่านปัจจุบัน",
    profileNewPassword: "รหัสผ่านใหม่",
    profileConfirmPassword: "ยืนยันรหัสผ่านใหม่",
    profileSaving: "กำลังบันทึก...",
    profileSaveChanges: "บันทึกการเปลี่ยนแปลง",
    profileUpdateSuccess: "ข้อมูลโปรไฟล์ถูกอัปเดตเรียบร้อยแล้ว",
    profileLoadFailed:
      "เกิดข้อผิดพลาดในการโหลดโปรไฟล์ผู้ใช้งาน กรุณาลองใหม่อีกครั้ง",
    profileUsernameEmpty: "ชื่อ-นามสกุลต้องไม่ว่างเปล่า",
    currentPasswordRequired: "กรุณากรอกรหัสผ่านปัจจุบัน",
    profileUpdateFailed:
      "เกิดข้อผิดพลาดในการอัปเดตข้อมูลโปรไฟล์ กรุณาลองใหม่อีกครั้ง",
    profileLeaderLabel: "หัวหน้า",
    profileLeaderPlaceholder: "-- เลือกหัวหน้า --",
    profileLeaderLockedNotice:
      "คุณได้เลือกหัวหน้าไปแล้วและไม่สามารถเปลี่ยนแปลงได้",
    profileLeaderNotice:
      "สามารถเลือกหัวหน้าได้เพียงครั้งเดียว เมื่อบันทึกแล้วจะไม่สามารถแก้ไขได้",
    myTask: "งานของฉัน",
    personalTask: "งานส่วนตัว",
    themes: "ธีมและหน้าตา",
    appearance: "โหมดการแสดงผล",
    appearanceLight: "สว่าง",
    appearanceDark: "มืด",
    appearanceAuto: "ตามระบบ",
    clickupTheme: "ชุดสีไฮไลต์",
    accentBlue: "สีฟ้า",
    accentPurple: "สีม่วง",
    accentPink: "สีชมพู",
    accentViolet: "สีไวโอเล็ต",
    accentIndigo: "สีคราม",
    accentOrange: "สีส้ม",
    accentTeal: "สีเขียวหัวเป็ด",
    accentBronze: "สีบรอนซ์",
    accentMint: "สีมินต์",
    accentGold: "สีทอง",
    myActivity: "กิจกรรมของฉัน",
    myActivitySubtitle: "ดูประวัติกิจกรรมการทำงานส่วนตัวของคุณ",
    signOut: "ออกจากระบบ",
    login: "เข้าสู่ระบบ",
    loading: "กำลังโหลด...",
    notifications: "การแจ้งเตือน",
    markAllAsRead: "อ่านทั้งหมดแล้ว",
    noNotifications: "ยังไม่มีการแจ้งเตือน",
    unread: "ยังไม่อ่าน",
    all: "ทั้งหมด",
    clearAll: "ล้างทั้งหมด",
    justNow: "เพิ่งเมื่อครู่",
    minutesAgo: "นาทีที่แล้ว",
    hoursAgo: "ชม.ที่แล้ว",
    daysAgo: "วันที่แล้ว",
    deleteNotification: "ลบ",
    newTaskAssigned: "งานใหม่ที่ได้รับมอบหมาย",
    projectStatusUpdated: "อัปเดตสถานะโปรเจกต์",
    systemNotification: "แจ้งเตือนจากระบบ",

    notifAssignedTeamLeader: "คุณได้รับมอบหมายเป็น Team Leader",
    notifAssignedTeamLeaderMsg:
      'คุณได้รับมอบหมายให้เป็นหัวหน้าโปรเจกต์ "{project}"',
    notifNewTaskInProject: "งานใหม่ในโปรเจกต์",
    notifNewTaskInProjectMsg: 'มีงานใหม่ "{task}" ในโปรเจกต์ "{project}"',
    notifNewTaskAssignedMsg:
      'คุณได้รับมอบหมายงานใหม่: "{task}" ในโปรเจกต์ "{project}"',
    notifTaskStatusUpdated: "อัปเดตสถานะงาน",
    notifTaskStatusUpdatedMsg:
      'งาน "{task}" ในโปรเจกต์ "{project}" ถูกอัปเดตสถานะเป็น "{status}"',
    notifProjectUpdated: "อัปเดตข้อมูลโปรเจกต์",
    notifProjectUpdatedMsg: 'โปรเจกต์ "{project}" มีการอัปเดตข้อมูลใหม่',
    notifProjectReviewing: "โปรเจกต์รอตรวจสอบ",
    notifProjectReviewingMsg:
      'โปรเจกต์ "{project}" มีสถานะเป็นรอการตรวจสอบ (Reviewing)',
    notifNewComment: "ความคิดเห็นใหม่ในงาน",
    notifNewCommentMsg: 'มีความคิดเห็นใหม่ในงาน "{task}"',
    personalTask: "งานส่วนตัว",

    // Login Page
    loginTitle: "เข้าสู่ระบบ",
    emailLabel: "อีเมล",
    passwordLabel: "รหัสผ่าน",
    emailPlaceholder: "ป้อนอีเมลของคุณ",
    passwordPlaceholder: "ป้อนรหัสผ่านของคุณ",
    fillAllFields: "กรุณากรอกข้อมูลให้ครบทุกช่อง",
    loginSuccess: "เข้าสู่ระบบสำเร็จ! กำลังนำทางไปยังหน้าแรก...",
    loginFailed: "การเข้าสู่ระบบล้มเหลว โปรดลองอีกครั้ง",
    invalidCredentials: "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
    accountSuspended: "บัญชีของคุณถูกระงับการใช้งาน กรุณาติดต่อผู้ดูแลระบบ",
    accountExpired: "บัญชีของคุณหมดอายุการใช้งานแล้ว กรุณาติดต่อผู้ดูแลระบบ",
    accountNotStarted: "บัญชีนี้จะเริ่มใช้งานได้ตั้งแต่วันที่ {startDate}",
    forgotPasswordLink: "ลืมรหัสผ่าน?",
    resetPasswordTitle: "รีเซ็ตรหัสผ่าน",
    newPasswordLabel: "รหัสผ่านใหม่",
    confirmPasswordLabel: "ยืนยันรหัสผ่านใหม่",
    resetSuccess: "รีเซ็ตรหัสผ่านสำเร็จ! กำลังนำทางไปยังหน้าล็อกอิน...",
    passwordsMismatch: "รหัสผ่านไม่ตรงกัน!",
    otpCodeLabel: "รหัส OTP",
    otpCodePlaceholder: "กรอกรหัส OTP 6 หลัก",
    sendOtpBtn: "ส่งรหัส OTP",

    // Home Page
    homeMessage: "หน้าแรกสำหรับผู้ใช้ทั่วไป",

    // Dashboard Page
    dashboardTitle: "แดชบอร์ด",
    allUsers: "ผู้ใช้ทั้งหมด",
    allMyTasks: "งานทั้งหมดของฉัน",
    manageUsersLink: "จัดการผู้ใช้ →",
    allProjects: "โปรเจคทั้งหมด",
    viewProjectsLink: "ดูโปรเจค →",
    totalTasks: "งานทั้งหมด",
    completedPrefix: "เสร็จแล้ว: ",
    overdueTasks: "งานเกินกำหนด",
    overdueProjects: "โปรเจกต์เกินกำหนด",
    actionRequired: "ต้องดำเนินการด่วน",
    taskStatus: "สถานะงาน",
    projectStatus: "สถานะโปรเจกต์",
    pending: "รอดำเนินการ",
    inProgress: "กำลังดำเนินการ",
    reviewing: "รอตรวจสอบ",
    completed: "เสร็จสิ้น",
    recentActivity: "กิจกรรมล่าสุด",
    systemAdmin: "ผู้ดูแลระบบ",
    loggedIn: "เข้าสู่ระบบ",
    minuteAgo: "1 นาทีที่แล้ว",
    viewAll: "ดูทั้งหมด",

    // Dashboard Cards
    manageUsersBtn: "จัดการผู้ใช้งาน",
    projectsTitle: "โปรเจกต์",
    reportsTitle: "รายงาน",
    "Project Calendar Title": "ปฏิทินกำหนดส่งงานโปรเจกต์",
    "Create New Project": "สร้างโปรเจกต์ใหม่",
    "Edit Project": "แก้ไขโปรเจกต์",
    "Create Task": "สร้างงานใหม่",
    "Edit Task": "แก้ไขงาน",
    projectCalendarDesc:
      "ติดตามกำหนดส่งงานและสถานะของแต่ละโครงการอย่างเป็นระบบ",

    // ManageUsers Page
    manageUsersTitle: "จัดการผู้ใช้งาน",
    addUserBtn: "เพิ่มผู้ใช้",
    roleFilterAll: "ทุกบทบาท",
    statusFilterAll: "ทุกสถานะ",
    activeLabel: "ใช้งานอยู่",
    suspendedLabel: "ถูกพักใช้งาน",
    searchUser: "ค้นหาผู้ใช้งาน",
    searchPlaceholder: "ค้นหาด้วยชื่อหรืออีเมล...",
    searchBtn: "ค้นหา",
    showText: "แสดง",
    entriesPerPageText: "รายการ",
    searchText: "ค้นหา:",
    colUser: "ผู้ใช้",
    colEmail: "อีเมล",
    colRole: "บทบาท",
    colStatus: "สถานะ",
    colLastLogin: "เข้าใช้งานล่าสุด",
    colManage: "จัดการ",
    noUsersText: "ไม่พบผู้ใช้งาน",
    showingText: "แสดง",
    toText: "ถึง",
    ofText: "จาก",
    entriesText: "รายการ",
    prevText: "ก่อนหน้า",
    nextText: "ถัดไป",
    importUsersBtn: "นำเข้าผู้ใช้งาน",
    downloadTemplateBtn: "ดาวน์โหลดไฟล์ตัวอย่าง",
    importSuccess: "นำเข้า/อัปเดตข้อมูลผู้ใช้งานเรียบร้อยแล้ว!",
    importFailed: "การนำเข้าข้อมูลล้มเหลว!",
    importConfirmTitle: "ยืนยันการนำเข้าผู้ใช้งาน",
    importConfirmDesc:
      "คุณแน่ใจหรือไม่ว่าต้องการนำเข้าผู้ใช้งานจากไฟล์ {filename}? (พบข้อมูลทั้งหมด {count} รายการ)",
    importResultTitle: "นำเข้าข้อมูลเสร็จสิ้น",
    importResultDesc:
      "นำเข้าผู้ใช้งานใหม่สำเร็จ {imported} คน และอัปเดตผู้ใช้งานเดิม {updated} คน",
    importPreviewTitle: "ตรวจสอบข้อมูลก่อนนำเข้า",
    importPreviewSub: "ไฟล์:",
    importPreviewTotal: "ทั้งหมด",
    importTotalCount: "รายการทั้งหมด",
    importNewUsers: "เพิ่มผู้ใช้ใหม่",
    importUpdateUsers: "อัปเดตข้อมูลเดิม",
    importChangedUsers: "ข้อมูลเปลี่ยนแปลง",
    importUnchangedUsers: "ไม่มีการแก้ไข",
    importInvalidUsers: "ข้อมูลไม่สมบูรณ์",
    importActionCol: "ผลลัพธ์การนำเข้า",
    importActionCreate: "สร้างใหม่",
    importActionUpdate: "อัปเดตเดิม",
    importActionChanged: "อัปเดต (ข้อมูลเปลี่ยน)",
    importActionUnchanged: "ข้อมูลเดิม (ข้าม)",
    importActionInvalid: "ข้าม / ไม่สมบูรณ์",
    importConfirmSummary: "พร้อมนำเข้าทั้งหมด",
    importChangedOnlyNotice: "ระบบจะบันทึกเฉพาะรายการใหม่และรายการที่มีการเปลี่ยนแปลง เพื่อความรวดเร็วและลดโหลดฐานข้อมูล",
    importInvalidSkipped: "ระบบจะข้ามรายการที่ไม่สมบูรณ์",
    importingProgress: "กำลังนำเข้าข้อมูล...",
    exportUsersBtn: "ส่งออกผู้ใช้งาน",

    // ManageUsers Modal
    addEditUserTitle: "เพิ่ม / แก้ไขผู้ใช้",
    editUserTitle: "แก้ไขข้อมูลผู้ใช้",
    addUserTitle: "เพิ่มผู้ใช้ใหม่",
    backBtn: "← กลับ",
    modalEmailLabel: "อีเมล",
    modalPasswordLabel: "รหัสผ่าน",
    modalPasswordPlaceholder: "ตั้งรหัสผ่าน",
    modalPasswordEditPlaceholder: "เว้นว่างไว้หากไม่ต้องการเปลี่ยน",
    modalFirstNameLabel: "ชื่อ",
    modalLastNameLabel: "นามสกุล",
    modalPhoneLabel: "เบอร์โทรศัพท์",
    modalStartDateLabel: "วันเริ่มใช้งาน",
    modalExpireDateLabel: "วันหมดอายุ",
    modalStartDatePlaceholder: "ไม่ระบุ (เริ่มทันที)",
    modalExpireDatePlaceholder: "ไม่ระบุ (ไม่มีวันหมดอายุ)",
    colValidity: "ระยะเวลาใช้งาน",
    validForever: "ไม่มีวันหมดอายุ",
    expiredLabel: "หมดอายุแล้ว",
    notStartedLabel: "ยังไม่ถึงวันเริ่ม",
    modalAvatarLabel: "รูปโปรไฟล์",
    modalChoosePhoto: "เลือกรูป",
    modalRemovePhoto: "ลบรูป",
    modalRoleLabel: "บทบาท",
    modalLeaderLabel: "หัวหน้า",
    modalLeaderPlaceholder: "-- Clear --",
    modalActiveLabel: "ใช้งานอยู่",
    modalCancelBtn: "ยกเลิก",
    modalSaveBtn: "บันทึกการแก้ไข",
    modalCreateBtn: "สร้างผู้ใช้",
    uploadPhotoBtn: "อัปเดตภาพ",
    modalStatusLabel: "สถานะ",
    statusActive: "ใช้งาน",
    statusSuspended: "ระงับการใช้งาน",
    cannotChangeSelfStatus: "ไม่สามารถเปลี่ยนสถานะของตนเองได้",
    youBadge: "คุณ",
    leaderBadge: "หัวหน้า",

    // ManageUsers messages
    fillRequiredFields: "กรุณากรอกข้อมูลดาว (*) ให้ครบถ้วน",
    userUpdatedSuccess: "อัปเดตข้อมูลผู้ใช้เรียบร้อยแล้ว!",
    userCreatedSuccess: "สร้างบัญชีผู้ใช้ใหม่เรียบร้อยแล้ว!",
    userAddFailed: "ไม่สามารถเพิ่มผู้ใช้งานได้",
    userUpdateFailed: "ไม่สามารถแก้ไขข้อมูลผู้ใช้งานได้",
    suspendConfirm: "คุณต้องการพักใช้งานผู้ใช้",
    activateConfirm: "คุณต้องการเปิดใช้งานผู้ใช้",
    confirmSuffix: "ใช่หรือไม่?",
    statusChangeFailed: "ไม่สามารถเปลี่ยนสถานะผู้ใช้ได้",
    deleteConfirm: "คุณแน่ใจหรือไม่ว่าต้องการลบผู้ใช้",
    deleteSuffix: "ออกจากระบบอย่างถาวร?",
    deleteFailed: "ไม่สามารถลบผู้ใช้ได้",
    fillRequiredFieldsProject:
      "กรุณากรอกข้อมูลให้ครบถ้วนทุกช่อง (Title, End Date, Team Leader)",
    projectCreatedSuccess:
      "สร้างโปรเจกต์ใหม่และส่งการแจ้งเตือนไปยัง Team Leader สำเร็จ!",
    projectCreateFailed: "ไม่สามารถสร้างโปรเจกต์ได้",
    projectUpdatedSuccess: "แก้ไขข้อมูลโปรเจกต์สำเร็จ!",
    projectUpdateFailed: "ไม่สามารถแก้ไขข้อมูลโปรเจกต์ได้",
    noPermissionDeleteProject: "ไม่มีสิทธิ์ลบโปรเจกต์ (เฉพาะ Admin เท่านั้น)",
    projectDeletedSuccess: "ลบโปรเจกต์พร้อมข้อมูลที่เกี่ยวข้องทั้งหมดสำเร็จ!",
    projectDeleteFailed: "ไม่สามารถลบโปรเจกต์ได้",
    editProjectTitle: "แก้ไขโปรเจกต์",
    modalProjectTitle: "หัวข้อโปรเจกต์",
    modalProjectStatus: "สถานะ",
    modalProjectPriority: "ระดับความสำคัญ",
    modalProjectEndDate: "วันที่สิ้นสุด",
    modalProjectTeamLeader: "หัวหน้าทีม",
    modalSaveProject: "บันทึกการแก้ไข",
    projectDetailsTitle: "รายละเอียดโปรเจกต์",
    projectDetailsName: "ชื่อโปรเจกต์",
    projectDetailsDueDate: "กำหนดส่ง",
    projectDetailsLeader: "หัวหน้าทีมผู้รับผิดชอบ",
    projectDetailsManager: "Project Manager",
    projectDetailsProgress: "ความคืบหน้าโดยรวม",
    projectDetailsTaskList: "รายการงานในโปรเจกต์",
    projectDetailsNoTasks: "ไม่มีงานที่ต้องทำในโปรเจกต์นี้",
    projectDetailsClose: "ปิดหน้าต่าง",
    projectDetailsEdit: "แก้ไขโปรเจกต์นี้",
    "Add Task": "เพิ่มงาน",

    // Projects Page
    projectManagementTitle: "จัดการโปรเจกต์",
    projectFlowSubtitle: "หน้าจัดการโปรเจกต์ตาม Flowchart",
    searchProjectPlaceholder: "ค้นหาโปรเจกต์ด้วยชื่อ...",
    createProjectBtn: "+ สร้างโปรเจกต์ใหม่",
    createProjectTitle: "สร้างโปรเจกต์ใหม่",
    createProjectBtnSubmit: "สร้างโปรเจกต์",
    projectListTitle: "รายการโปรเจกต์",
    colProjectName: "ชื่อโปรเจกต์",
    colProgress: "ความคืบหน้า",
    colPriority: "ระดับความสำคัญ",
    colTeamLeader: "หัวหน้าทีม",
    colDetailAction: "รายละเอียด / การจัดการ",
    viewBtn: "ดูรายละเอียด",
    editBtn: "แก้ไข",
    deleteBtn: "ลบ",
    noProjectsFound: "ไม่พบข้อมูลโปรเจกต์",
    tableView: "แสดงแบบตาราง",
    boardView: "แสดงแบบบอร์ด",
    statusPending: "รอดำเนินการ",
    statusInProgress: "กำลังดำเนินการ",
    statusReview: "รอตรวจสอบ",
    statusCompleted: "เสร็จสิ้น",
    deleteUserConfirmTitle: "ยืนยันการลบผู้ใช้?",
    endDateLabel: "วันสิ้นสุด",
    deleteProjectConfirmTitle: "ยืนยันการลบโปรเจกต์?",
    deleteProjectConfirmDesc1: "ระบบจะทำการลบข้อมูลโปรเจกต์ ",
    deleteProjectConfirmDesc2:
      " และทำการ Cascade Delete ข้อมูลที่เกี่ยวโยงทั้งหมด (Tasks, Comments, Files)",
    deleteUserSuccess: "ลบข้อมูลผู้ใช้งานเรียบร้อยแล้ว!",
    cancelBtn: "ยกเลิก",
    confirmDeleteBtn: "ยืนยันการลบ",
    confirmBtn: "ยืนยัน",
    sortByPriorityLabel: "เรียงตามความสำคัญ",
    sessionTimeoutTitle: "การแจ้งเตือนเซสชันหมดอายุ",
    sessionTimeoutDesc:
      "เซสชันการเข้าใช้งานของคุณจะหมดอายุในอีก {seconds} วินาที คุณต้องการใช้เว็บไซต์ต่อหรือจะออกจากระบบ?",
    sessionTimeoutStayBtn: "ใช้งานต่อ",
    sessionTimeoutExitBtn: "ออกจากระบบ",
    "Create Task": "สร้างงาน",

    // Activity Page
    activityLogsTitle: "บันทึกกิจกรรมของระบบ",
    activityLogsSubtitle:
      "ตรวจสอบและติดตามประวัติการทำรายการกิจกรรมทั้งหมดของระบบ",
    searchActivityPlaceholder: "ค้นหารายละเอียด...",
    allActivities: "กิจกรรมทั้งหมด",
    aboutProjects: "เกี่ยวกับโปรเจกต์และงาน",
    aboutUsers: "เกี่ยวกับผู้ใช้งาน",
    aboutSystem: "เกี่ยวกับระบบ / อื่น ๆ",
    refreshBtn: "รีเฟรชข้อมูล",
    loadingActivities: "กำลังโหลดบันทึกกิจกรรม...",
    colDoneBy: "ทำรายการโดย:",
    firstTimeResetTitle: "เปลี่ยนรหัสผ่านครั้งแรก",
    firstTimeResetDesc:
      "กรุณาเปลี่ยนรหัสผ่านเพื่อความปลอดภัยก่อนเริ่มต้นใช้งาน",
    updatingPassword: "กำลังเปลี่ยนรหัสผ่าน...",
    saveNewPassword: "บันทึกรหัสผ่านใหม่",
    firstTimeResetSuccess:
      "เปลี่ยนรหัสผ่านสำเร็จ! กำลังนำคุณเข้าสู่หน้าแดชบอร์ด...",
    firstTimeResetFailed: "เกิดข้อผิดพลาดในการเปลี่ยนรหัสผ่าน",
    forceResetPrompt: "กรุณาเปลี่ยนรหัสผ่านก่อนเข้าใช้งานครั้งแรก",
    unassigned: "ยังไม่ได้ระบุผู้รับผิดชอบ",
    viewTaskDetail: "ดูรายละเอียดงาน",
    Login: "เข้าสู่ระบบ",
    "Create New Project": "สร้างโปรเจกต์ใหม่",
    "Edit Project": "แก้ไขโปรเจกต์",
    "Delete Project": "ลบโปรเจกต์",
    "Create Task Success": "สร้างงานใหม่",
    "Update Task Status": "อัปเดตสถานะงาน",
    "Update Task Details": "อัปเดตรายละเอียดงาน",
    "Edit Task": "แก้ไขงาน",
    "Delete Task": "ลบงาน",
    Logout: "ออกจากระบบ",
    "Reset Password": "รีเซ็ตรหัสผ่าน",
    "Reset Password First Time": "รีเซ็ตรหัสผ่านครั้งแรก",
    "Import Users": "นำเข้าข้อมูลผู้ใช้งาน",
    "Create User": "สร้างบัญชีผู้ใช้งานใหม่",
    "Edit User": "แก้ไขข้อมูลผู้ใช้งาน",
    "Delete User": "ลบผู้ใช้งาน",
    "Suspend User": "ระงับการใช้งานผู้ใช้",
    "Activate User": "เปิดใช้งานผู้ใช้",
    taskDetailsTitle: "รายละเอียดงาน",
    createTaskTitle: "สร้างงานใหม่",
    createTaskBtn: "สร้างงาน",
    taskProjectLabel: "โปรเจกต์",
    taskNameLabel: "ชื่องาน",
    taskNamePlaceholder: "กรอกชื่อกิจกรรม/งาน",
    taskTypeLabel: "ประเภทงาน",
    taskTypeTranslate: "แปล",
    taskTypeStoryboard: "สตอรี่บอร์ด",
    taskTypeGraphicDesign: "ออกแบบกราฟิก",
    taskTypeAnimation: "อนิเมชัน",
    taskTypeVideoEdit: "ตัดต่อ",
    taskTypeDevelopment: "พัฒนาโปรแกรม",
    taskTypeOthers: "อื่นๆ",
    customTaskTypeLabel: "ระบุประเภทงานเพิ่มเติม *",
    customTaskTypePlaceholder: "ระบุประเภทงานเพิ่มเติมของคุณ",
    taskDescLabel: "รายละเอียด",
    taskDescPlaceholder: "กรอกรายละเอียดงาน",
    taskPriorityLabel: "ความสำคัญ",
    priorityHigh: "สูง",
    priorityMedium: "ปานกลาง",
    priorityLow: "ต่ำ",
    optionalText: "ระบุหรือไม่ก็ได้",
    taskDueDateLabel: "วันส่งงาน",
    taskAssigneeLabel: "ผู้รับผิดชอบ",
    selectAssignee: "เลือกผู้รับผิดชอบ",
    taskStatusLabel: "สถานะงาน",
    noDescription: "-- ไม่มีรายละเอียด --",
    noAssignee: "-- ไม่ระบุผู้รับผิดชอบ --",
    updateStatusBtn: "อัปเดตสถานะ",
    taskStatusPending: "รอดำเนินการ",
    taskStatusInProgress: "กำลังทำ",
    taskStatusReviewing: "รอตรวจสอบ",
    taskStatusCompleted: "เสร็จสมบูรณ์",
    manageUsersDesc: "จัดการผู้ใช้งานและสิทธิ์การเข้าถึงระบบ",
    projectManagementDesc: "บริหารจัดการโครงการและทีมงานที่รับผิดชอบ",

    // About & Contract Pages
    aboutTitle: "เกี่ยวกับระบบ RNM Task",
    aboutSubtitle: "แพลตฟอร์มยุคใหม่สำหรับการบริหารจัดการโครงการและงานในทีม",
    aboutVisionTitle: "วิสัยทัศน์และเป้าหมายของเรา",
    aboutVisionDesc:
      "RNM Task Management ถูกออกแบบมาเพื่อยกระดับการทำงานร่วมกันของทีม เพิ่มความโปร่งใสในโครงการ และจัดระเบียบขั้นตอนการทำงานด้วยระบบอัปเดตแบบเรียลไทม์และบันทึกประวัติกิจกรรมอย่างละเอียด",
    featureAnalyticsTitle: "ระบบวิเคราะห์ & แดชบอร์ดเรียลไทม์",
    featureAnalyticsDesc:
      "ติดตามสถิติผู้ใช้งาน โครงการ และงานที่เกินกำหนดได้อย่างแม่นยำผ่านกราฟภาพรวม",
    featureWorkflowTitle: "ผังการทำงานที่เป็นระบบ",
    featureWorkflowDesc:
      "จัดกลุ่มงานตามสถานะ (รอดำเนินการ, กำลังดำเนินการ, รอตรวจสอบ, เสร็จสิ้น) พร้อมกำหนดระดับความสำคัญ",
    featureAccessTitle: "ระบบกำหนดสิทธิ์ตามบทบาท",
    featureAccessDesc:
      "จัดการสิทธิ์การเข้าถึงอย่างปลอดภัยสำหรับ แอดมิน, หัวหน้าทีม, นักแปล, และนักตัดต่อวิดีโอ",
    featureAuditTitle: "บันทึกประวัติกิจกรรมครบถ้วน",
    featureAuditDesc:
      "ติดตามทุกการเปลี่ยนแปลงของโครงการ การสร้างผู้ใช้งาน และการอัปเดตสถานะงานอย่างโปร่งใส",
    techStackTitle: "พัฒนาด้วยเทคโนโลยีทันสมัย",

    contractTitle: "ติดต่อเรา & สนับสนุนการใช้งาน",
    contractSubtitle:
      "มีข้อสงสัยเกี่ยวกับระบบ หรือต้องการสอบถามข้อมูลเพิ่มเติม ติดต่อทีมงานของเราได้ตลอดเวลา",
    contactInfoTitle: "ข้อมูลการติดต่อ",
    contactAddressLabel: "ที่อยู่สำนักงาน",
    contactAddressVal: "------------",
    contactEmailLabel: "อีเมลสนับสนุน",
    contactPhoneLabel: "เบอร์โทรศัพท์ติดต่อ",
    contactHoursLabel: "เวลาทำการ",
    contactHoursVal: "จันทร์ - ศุกร์: 09:00 - 18:00 น.",
    sendMessageTitle: "ส่งข้อความถึงเรา",
    formFullName: "ชื่อ-นามสกุล",
    formFullNamePlaceholder: "กรอกชื่อ-นามสกุลของคุณ",
    formEmail: "อีเมลติดต่อ",
    formEmailPlaceholder: "กรอกอีเมลของคุณ",
    formSubject: "หัวข้อเรื่อง",
    formSubjectPlaceholder: "ระบุหัวข้อเรื่องที่ต้องการสอบถาม",
    formMessage: "ข้อความ",
    formMessagePlaceholder: "กรอกรายละเอียดข้อความของคุณ...",
    sendMessageBtn: "ส่งข้อความ",
    sendMessageSuccess:
      "ขอบคุณสำหรับการติดต่อ! ข้อความของคุณถูกส่งเรียบร้อยแล้ว ทีมงานจะติดต่อกลับโดยเร็วที่สุด",
    colDetails: "รายละเอียด",
    colAction: "การจัดการ",
    colTime: "เวลา",
    landingBadge: "🚀 แพลตฟอร์มจัดการโปรเจกต์และงานสำหรับทีมยุคใหม่",
    landingHeroTitle: "บริหารจัดการโปรเจกต์และงานในทีม",
    landingHeroTitleAccent: "ง่าย ครบจบในที่เดียว และเป็นระบบ",
    landingHeroDesc:
      "ช่วยให้ทีมของคุณทำงานร่วมกันได้อย่างราบรื่น ติดตามกำหนดส่งงานผ่านปฏิทิน อัปเดตสถานะงานได้แบบเรียลไทม์ พร้อมบันทึกประวัติการทำงานของระบบอย่างเป็นระเบียบ",
    goToDashboard: "เข้าสู่หน้าแดชบอร์ด",
    getStartedBtn: "เริ่มต้นใช้งานฟรี",
    learnMoreBtn: "เรียนรู้เพิ่มเติม",
    statProductivity: "เพิ่มประสิทธิภาพการทำงาน",
    statAlignment: "ทีมทำงานสอดคล้องกัน 100%",
    statMissedDeadlines: "ลดการส่งงานล่าช้ากว่ากำหนด",
    landingFeaturesTitle: "ฟีเจอร์เด่นที่จะช่วยให้งานคุณราบรื่น",
    landingFeaturesDesc:
      "ระบบของเราออกแบบมาอย่างพิถีพิถันเพื่อตอบโจทย์ทุกขั้นตอนในการบริหารจัดการงานและโครงการ",
    featureProjTitle: "จัดการโปรเจกต์",
    featureProjDesc:
      "สร้างโปรเจกต์หลัก กำหนดหัวหน้าทีม และติดตามความคืบหน้าของโปรเจกต์ได้โดยอัตโนมัติ",
    featureTaskTitle: "ติดตามสถานะงาน",
    featureTaskDesc:
      "ควบคุมสถานะของงานย่อยได้อย่างละเอียด ไม่ว่าจะเป็นงานที่รอดำเนินการ, กำลังทำ, อยู่ระหว่างตรวจสอบ หรือเสร็จสิ้นแล้ว",
    featureCalTitle: "ปฏิทินส่งงาน",
    featureCalDesc:
      "ดูวันส่งงานของทุกโปรเจกต์ได้บนปฏิทินแบบ Interactive ป้องกันการลืมวันส่งงานสำคัญ",
    featureTeamTitle: "บันทึกประวัติกิจกรรม",
    featureTeamDesc:
      "ตรวจสอบประวัติการทำงานย้อนหลังของทุกคนในระบบได้อย่างโปร่งใส รู้ทุกการอัปเดตและการเปลี่ยนแปลง",
    landingCtaTitle: "พร้อมที่จะยกระดับการทำงานของทีมคุณแล้วหรือยัง?",
    landingCtaDesc:
      "เริ่มต้นจัดการโปรเจกต์ของคุณอย่างเป็นระบบตั้งแต่วันนี้ ใช้งานได้ฟรี!",

    // Reports Page & Role Reports
    reportsHeaderTitle: "รายงานประสิทธิภาพส่วนบุคคล",
    reportsHeaderDesc:
      "วิเคราะห์และติดตามสรุปผลการทำงาน กำหนดส่ง และสัดส่วนภารกิจของฉัน",
    adminReportTitle: "รายงานภาพรวมผู้บริหารและวิเคราะห์ระบบ",
    adminReportDesc:
      "สรุปสถิติภาพรวมทั้งระบบ การดำเนินงานของโปรเจกต์ และภาระงานของบุคลากร",
    managerReportTitle: "รายงานวิเคราะห์การบริหารโครงการ",
    managerReportDesc:
      "ติดตามสถานะความคืบหน้าของโครงการที่ท่านบริหารและจัดการทีมงาน",
    teamLeaderReportTitle: "รายงานและสถิติการทำงานของทีม",
    teamLeaderReportDesc:
      "วิเคราะห์ประสิทธิภาพการดำเนินงาน ปริมาณงานคงค้าง และการส่งงานของลูกทีม",
    exportExcel: "ส่งออก Excel",
    printReport: "พิมพ์รายงาน",
    totalActiveUsers: "ผู้ใช้งานในระบบ",
    overallCompletionRateLabel: "อัตราความสำเร็จภาพรวม",
    systemDeliveryEfficiency: "อัตราการส่งงานสำเร็จ",
    systemDeliveryDesc: "สัดส่วนงานที่เสร็จสิ้นเปรียบเทียบกับงานทั้งหมดในระบบ",
    projectStatusBreakdownTitle: "สถานะโครงการในระบบ",
    projectStatusBreakdownDesc:
      "แจกแจงสถานะของโครงการทั้งหมดที่กำลังดำเนินการในระบบ",
    userWorkloadMatrixTitle: "รายงานภาระงานและอัตราความสำเร็จของสมาชิก",
    userWorkloadMatrixDesc:
      "สรุปจำนวนงานที่ได้รับมอบหมายและเปอร์เซ็นต์ความสำเร็จของบุคลากรแต่ละคน",
    assignedTasksLabel: "งานที่ได้รับ",
    completedTasksLabel: "งานที่สำเร็จ",
    progressRateLabel: "อัตราความสำเร็จ",
    managedProjectsProgressTitle: "ความคืบหน้าของโครงการที่อยู่ในการดูแล",
    managedProjectsProgressDesc:
      "ติดตามสถานะ กำหนดส่ง และความคืบหน้าของโครงการที่ท่านรับผิดชอบ",
    onTrackProjectsLabel: "โครงการที่ดำเนินตามแผน",
    activeTeamTasksTitle: "สถานะการดำเนินงานของทีมที่กำลังทำอยู่",
    activeTeamTasksDesc: "การติดตามงานคงค้างและงานที่กำลังดำเนินการของลูกทีม",
    personalWorkRateTitle: "ประสิทธิภาพการส่งงานส่วนบุคคล",
    personalWorkRateDesc:
      "สัดส่วนงานที่ท่านทำสำเร็จเปรียบเทียบกับภารกิจทั้งหมด",
    workloadDistributionTypeTitle: "สัดส่วนจำแนกตามประเภทงาน",
    workloadDistributionTypeDesc:
      "แจกแจงปริมาณงานตามประเภทกิจกรรม เช่น งานแปล และ งานตัดต่อ",
    myTaskPerformanceSummaryTitle: "สรุปภารกิจของฉัน",
    myTaskPerformanceSummaryDesc:
      "ตารางสรุปรายการงานทั้งหมดที่ท่านรับผิดชอบพร้อมสถานะและกำหนดส่ง",
    managedProjectsCalendar: "ปฏิทินโปรเจกต์ที่ดูแล",
    managedProjectsCalendarDesc:
      "ติดตามกำหนดส่งและสถานะโปรเจกต์ที่คุณเป็น Team Leader",
    myTaskCalendar: "ปฏิทินงานของฉัน",
    myTaskCalendarDesc: "ติดตามกำหนดส่งงานและสถานะงานของฉัน",
    editTaskInfoBtn: "แก้ไขข้อมูล",
    refreshDataBtn: "รีเฟรชข้อมูล",
    refreshBtn: "รีเฟรชข้อมูล",
    assignedTasksText: "งานที่ได้รับมอบหมาย",
    manageTaskBtn: "จัดการ",
    noAssignedTasksText: "ไม่พบงานที่รับผิดชอบ",
    noActiveTeamTasksText: "ไม่มีงานที่กำลังดำเนินการในทีม",
    noManagedProjectsText: "ไม่มีโครงการภายใต้การดูแลในขณะนี้",
    // Personal Tasks Page & Components
    personalTaskPageTitle: "งานส่วนตัวของฉัน",
    personalTaskPageDesc:
      "จัดการรายการงานส่วนตัวของคุณด้วยระบบ Kanban บอร์ด และปฏิทิน ลาก & วาง",
    kanbanViewBtn: "บอร์ด",
    calendarViewBtn: "ปฏิทิน",
    addNewPersonalTaskBtn: "+ เพิ่มงานใหม่",
    editTaskPromptTitle: "แก้ไขงาน",
    newTaskPromptTitle: "สร้างงานใหม่",
    taskTitleLabel: "ชื่องาน",
    taskStatusLabel: "สถานะ",
    dueDateOptionalLabel: "กำหนดส่ง (ไม่บังคับ)",
    deleteTaskConfirmTitle: "ต้องการลบงานนี้หรือไม่?",
    deleteTaskConfirmText: "คุณแน่ใจหรือไม่ว่าต้องการลบงานนี้?",
    deleteTaskConfirmBtn: "ใช่, ลบเลย",
    taskDeletedSuccess: "ลบงานสำเร็จ",
    taskUpdatedSuccess: "อัปเดตข้อมูลงานสำเร็จ",
    taskCreatedSuccess: "สร้างงานใหม่สำเร็จ",
    noUnscheduledTasks:
      "ไม่มีงานค้าง (คุณสามารถลากงานจากบนปฏิทินลงมาวางที่นี่เพื่อยกเลิกกำหนดส่งได้)",
    unscheduledTasksTrayTitle: "งานที่ยังไม่ได้กำหนดส่ง",
    unscheduledTasksTrayDesc:
      "ลากงานขึ้นปฏิทินเพื่อใส่วันที่ หรือลากงานจากปฏิทินลงมาที่นี่เพื่อยกเลิกกำหนดส่ง",
    dragBadge: "ลากวาง",
    editTaskTooltip: "แก้ไขงานนี้",
    deleteTaskTooltip: "ลบงานนี้",
    saveChangesBtn: "บันทึกข้อมูล",
    cancelBtnText: "ยกเลิก",
    confirmBtnText: "ยืนยัน",
    okBtnText: "ตกลง",
    // Reset Password & Auth
    resetPasswordSubtitle: "กรอกข้อมูลและรหัส OTP เพื่อตั้งรหัสผ่านใหม่",
    backToLoginBtn: "← กลับไปหน้าล็อกอิน",
    sendOtpSuccess: "ส่งรหัส OTP ไปยังอีเมลของคุณเรียบร้อยแล้ว!",
    sendOtpFailed: "ไม่สามารถส่ง OTP ได้",
    otpVerifyFailed: "รหัส OTP ไม่ถูกต้องหรือหมดอายุ",
    welcomeBackPortal: "ยินดีต้อนรับสู่ระบบบริหารงาน",

    // Project & Task Modals & Tables
    colProjectNameUpper: "ชื่อโครงการ",
    colTeamLeaderUpper: "หัวหน้าทีม",
    colPriorityUpper: "ความสำคัญ",
    colStatusUpper: "สถานะ",
    colDueDateUpper: "วันสิ้นสุด",
    colActionUpper: "จัดการ",
    manageActionBtn: "จัดการ",
    editTaskInfo: "แก้ไขข้อมูลงาน",
    statusHistoryTitle: "ประวัติการเปลี่ยนสถานะ",
    searchTaskOrProjectPlaceholder: "ค้นหาชื่องาน หรือ โปรเจกต์...",
    allFilterOption: "ทั้งหมด",
    totalTasksLabel: "งานทั้งหมด",
    noTasksFoundForUser: "ไม่พบงานที่รับผิดชอบ",
    noTasksFoundDesc: "คุณยังไม่มีงานที่ได้รับมอบหมายในสถานะนี้หรือคำค้นหานี้",
    noTasksInCategory: "ไม่พบรายการงานในหมวดหมู่นี้",
    noProjectsInCategory: "ไม่พบโครงการในหมวดหมู่นี้",
    activeCategoryLabel: "กำลังดำเนินการ",
    completedCategoryLabel: "เสร็จสิ้น",
    allCategoryLabel: "ทั้งหมด",
    // Report Tables & Performance (TH)
    myTaskPerformanceSummaryTitle: "สรุปผลการปฏิบัติงานส่วนตัว",
    myTaskPerformanceSummaryDesc:
      "รายการงานทั้งหมดที่คุณได้รับมอบหมายพร้อมสถานะการดำเนินงาน",
    personalWorkRateTitle: "อัตราความสำเร็จของงาน",
    personalWorkRateDesc: "เปอร์เซ็นต์งานที่คุณทำเสร็จสิ้นเทียบกับงานทั้งหมด",
    workloadDistributionTypeTitle: "การกระจายภาระงานตามประเภท",
    workloadDistributionTypeDesc: "สัดส่วนปริมาณงานของคุณจำแนกตามประเภทของงาน",
    personalReport: "รายงานส่วนตัว",
    teamLeaderReport: "รายงานหัวหน้าทีม",
    managerReport: "รายงาน Project Manager",
    adminReport: "รายงานผู้ดูแลระบบ",
    adminReportTitle: "รายงานภาพรวมผู้ดูแลระบบ",
    adminReportDesc:
      "ข้อมูลสถิติภาพรวมทุกโครงการ งาน และภาระงานของทีมทั้งหมดในระบบ",
    managerReportTitle: "รายงาน Project Manager",
    managerReportDesc:
      "ภาพรวมโครงการที่ดูแล ความคืบหน้า และประสิทธิภาพการส่งมอบงาน",
    teamLeaderReportTitle: "รายงานหัวหน้าทีมและวิเคราะห์โครงการ",
    teamLeaderReportDesc: "ภาพรวมโครงการและงานที่สมาชิกในทีมกำลังดำเนินงาน",
    teamStatusDistribution: "สัดส่วนสถานะงานของทีม",
    teamStatusDistributionDesc:
      "ภาพรวมการกระจายสถานะของงานทั้งหมดที่สมาชิกในทีมรับผิดชอบ",
    teamMemberWorkloadTitle: "ภาระงานและความสำเร็จของสมาชิกในทีม",
    teamMemberWorkloadDesc:
      "เปรียบเทียบจำนวนงานที่ได้รับมอบหมายและงานที่ทำเสร็จของสมาชิกแต่ละคน",
    projectHealthStatusTitle: "สัดส่วนสถานะโครงการ",
    projectHealthStatusDesc:
      "ภาพรวมการกระจายตัวของโครงการที่ดูแลตามสถานะการดำเนินงาน",
    projectProgressOverviewTitle: "ความคืบหน้าและการส่งมอบโครงการ",
    projectProgressOverviewDesc:
      "เปอร์เซ็นต์ความสำเร็จของแต่ละโครงการที่อยู่ในความดูแล",
    taskNameLabel: "ชื่องาน",
    taskProjectLabel: "โครงการ",
    taskTypeLabel: "ประเภทงาน",
    taskStatusLabel: "สถานะ",
    taskDueDateLabel: "กำหนดส่ง",
    priority: "ความสำคัญ",
    searchWork: "ค้นหางาน",
    searchWorkPlaceholder: "ค้นหาด้วยชื่องาน หรือชื่อโปรเจกต์...",
    allStatus: "ทุกสถานะ",
    allTaskTypes: "ทุกประเภทงาน",
    taskTypeAll: "ทุกประเภทงาน",
    statusFilterAll: "ทุกสถานะ",
    statusPending: "รอดำเนินการ",
    statusInProgress: "กำลังดำเนินการ",
    statusReview: "รอตรวจสอบ",
    statusCompleted: "เสร็จสิ้น",
    taskTypeTranslate: "แปล",
    taskTypeStoryboard: "สตอรี่บอร์ด",
    taskTypeGraphicDesign: "ออกแบบ",
    taskTypeAnimation: "อนิเมชัน",
    taskTypeVideoEdit: "ตัดต่อ",
    taskTypeDevelopment: "พัฒนาโปรแกรม",
    taskTypeOthers: "อื่นๆ",
    noMatchingTasksFound: "ไม่พบรายการงานที่ตรงตามเงื่อนไข",
    clearFilters: "ล้างตัวกรองทั้งหมด",
    noAssignedTasksText: "ไม่มีรายการงานที่ได้รับมอบหมาย",

    // Activity Log Actions (TH)
    Login: "เข้าสู่ระบบ",
    Logout: "ออกจากระบบ",
    "Create User": "สร้างผู้ใช้ใหม่",
    "Suspend User": "ระงับการใช้งานผู้ใช้",
    "Activate User": "เปิดใช้งานผู้ใช้",
    "Edit User": "แก้ไขข้อมูลผู้ใช้",
    "Soft Delete User": "ลบผู้ใช้",
    "Restore User": "กู้คืนผู้ใช้",
    "Permanent Delete User": "ลบผู้ใช้ถาวร",
    "Create New Project": "สร้างโปรเจกต์ใหม่",
    "Edit Project": "แก้ไขโปรเจกต์",
    "Delete Project": "ลบโปรเจกต์",
    "Create Task Success": "สร้างงานใหม่",
    "Create Task": "สร้างงานใหม่",
    "Update Task Status": "อัปเดตสถานะงาน",
    "Update Task Details": "แก้ไขข้อมูลงาน",
    "Delete Task": "ลบงาน",
    "Reset Password": "รีเซ็ตรหัสผ่าน",
    "Reset Password First Time": "เปลี่ยนรหัสผ่านครั้งแรก",
    "Send Email (Project Creation)": "ส่งอีเมลแจ้งมอบหมายโปรเจกต์",
    "Send Email Warning (Project Creation)":
      "แจ้งเตือนการส่งอีเมลมอบหมายโปรเจกต์",
    "Send Email Failed (Project Creation)": "ส่งอีเมลมอบหมายโปรเจกต์ไม่สำเร็จ",
    "Send Email (Task Creation)": "ส่งอีเมลแจ้งมอบหมายงาน",
    "Send Email Warning (Task Creation)": "แจ้งเตือนการส่งอีเมลมอบหมายงาน",
    "Send Email Failed (Task Creation)": "ส่งอีเมลมอบหมายงานไม่สำเร็จ",
    "Send Email (Welcome User)": "ส่งอีเมลต้อนรับผู้ใช้งาน",
    "Send Email Warning (Welcome User)": "แจ้งเตือนการส่งอีเมลต้อนรับผู้ใช้งาน",
    "Send Email Failed (Welcome User)": "ส่งอีเมลต้อนรับผู้ใช้งานไม่สำเร็จ",
    "Send Email (OTP)": "ส่งอีเมลรหัส OTP",
    "Send Email Warning (OTP)": "แจ้งเตือนการส่งอีเมลรหัส OTP",
    "Send Email Failed (OTP)": "ส่งอีเมลรหัส OTP ไม่สำเร็จ",
    "Send Email (Task Overdue to Leader)":
      "ส่งอีเมลแจ้งเตือนงานเกินกำหนดถึงหัวหน้าทีม",
    "Send Email Warning (Task Overdue to Leader)":
      "แจ้งเตือนการส่งอีเมลงานเกินกำหนด",
    "Send Email Failed (Task Overdue to Leader)":
      "ส่งอีเมลแจ้งเตือนงานเกินกำหนดไม่สำเร็จ",
    เข้าสู่ระบบ: "เข้าสู่ระบบ",
    ออกจากระบบ: "ออกจากระบบ",
    สร้างผู้ใช้: "สร้างผู้ใช้ใหม่",
    แก้ไขผู้ใช้: "แก้ไขข้อมูลผู้ใช้",
    ลบผู้ใช้: "ลบผู้ใช้",
    สร้างโปรเจกต์ใหม่: "สร้างโปรเจกต์ใหม่",
    แก้ไขโปรเจกต์: "แก้ไขโปรเจกต์",
    ลบโปรเจกต์: "ลบโปรเจกต์",
    สร้างงานใหม่: "สร้างงานใหม่",
    อัปเดตสถานะงาน: "อัปเดตสถานะงาน",
    แก้ไขงาน: "แก้ไขข้อมูลงาน",
    ลบงาน: "ลบงาน",
    รีเซ็ตรหัสผ่าน: "รีเซ็ตรหัสผ่าน",
    เปลี่ยนรหัสผ่านครั้งแรก: "เปลี่ยนรหัสผ่านครั้งแรก",

    // Personal Task Kanban & Columns
    "TO DO": "ต้องทำ",
    "IN PROGRESS": "กำลังทำ",
    COMPLETED: "เสร็จสิ้น",
    "To Do": "ต้องทำ",
    "In Progress": "กำลังทำ",
    Completed: "เสร็จสิ้น",
    ต้องทำ: "ต้องทำ",
    กำลังทำ: "กำลังทำ",
    เสร็จสิ้น: "เสร็จสิ้น",

    // Activity & Logs
    activityLogsTitle: "บันทึกประวัติกิจกรรม",
    activityLogsSubtitle: "ตรวจสอบและติดตามกิจกรรมการทำงาน การกระทำ และการอัปเดตในระบบ",
    searchActivityPlaceholder: "ค้นหากิจกรรมหรือรายละเอียด...",
    allActivities: "กิจกรรมทั้งหมด",
    aboutProjects: "โปรเจกต์และงาน",
    aboutUsers: "ผู้ใช้งาน",
    aboutSystem: "ระบบ",
    colAction: "การกระทำ",
    colDetails: "รายละเอียด",
    colTime: "เวลา",
    loadingActivities: "กำลังโหลดประวัติกิจกรรม...",
    noActivitiesFound: "ไม่พบประวัติกิจกรรม",
  },
};

/**
 * ผู้ให้บริการเปลี่ยนภาษาของระบบ (LanguageProvider Component)
 * - กำหนดสถานะภาษาเริ่มต้น (ค่าเริ่มต้นคือ ภาษาไทย 'th' ดึงจาก localStorage)
 * - บันทึกการเปลี่ยนแปลงค่าภาษาลงใน localStorage เมื่อค่าภาษาเปลี่ยน
 */
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "th";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  /**
   * ฟังก์ชันสำหรับสลับภาษาระหว่างภาษาไทย (th) และภาษาอังกฤษ (en)
   */
  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "th" : "en"));
  };

  /**
   * ฟังก์ชันแปลคำศัพท์ตาม Key ที่กำหนด
   * @param {string} key - คีย์เวิร์ดคำศัพท์
   * @returns {string} คำที่แปลแล้ว (หากไม่มีในพจนานุกรม จะคืนค่า key กลับไป)
   */
  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, toggleLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

/**
 * Custom Hook สำหรับเรียกใช้งานข้อมูลภาษาและการแปลคำศัพท์ในคอมโพเนนต์อื่น ๆ
 * @returns {{language: string, setLanguage: Function, toggleLanguage: Function, t: Function}}
 */
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
